/// A map representing the demo data for file import history.
Map<String, dynamic> kMockHistory_6_0_0 = {
  'version': '6.0.0',
  'position': 7,
  'history': [
    {
      'layers': [
        {'id': 'A'},
      ],
      'blur': 2.0,
    },
    {
      'layers': [
        {
          'id': 'A',
          'x': -71.60000000000002,
          'y': -90.39999999999998,
          'rotation': -0.523596,
          'scale': 2.5582142857142856,
        },
      ],
    },
    {
      'layers': [
        {'id': 'A'},
        {'id': 'B'},
      ],
    },
    {
      'layers': [
        {'id': 'A'},
        {'id': 'B', 'x': 58.0, 'y': -173.2, 'rotation': 0.43633, 'scale': 0.85},
      ],
    },
    {
      'layers': [
        {'id': 'A'},
        {'id': 'B'},
        {'id': 'C'},
      ],
    },
    {
      'layers': [
        {'id': 'A'},
        {'id': 'B'},
        {'id': 'C'},
      ],
      'filters': [
        [
          1.0,
          0.0,
          0.0,
          0.0,
          50.0,
          0.0,
          1.0,
          0.0,
          0.0,
          0.0,
          0.0,
          0.0,
          1.0,
          0.0,
          0.0,
          0.0,
          0.0,
          0.0,
          1.0,
          0.0,
        ],
        [
          1.0,
          0.0,
          0.0,
          0.0,
          0.0,
          0.0,
          1.0,
          0.0,
          0.0,
          0.0,
          0.0,
          0.0,
          1.0,
          0.0,
          0.0,
          0.0,
          0.0,
          0.0,
          0.29,
          0.0,
        ],
      ],
    },
    {
      'layers': [
        {'id': 'A'},
        {'id': 'B'},
        {'id': 'C'},
      ],
      'tune': [
        {
          'id': 'brightness',
          'value': 0.26,
          'matrix': [
            1.0,
            0.0,
            0.0,
            0.0,
            26.0,
            0.0,
            1.0,
            0.0,
            0.0,
            26.0,
            0.0,
            0.0,
            1.0,
            0.0,
            26.0,
            0.0,
            0.0,
            0.0,
            1.0,
            0.0,
          ],
        },
        {
          'id': 'contrast',
          'value': 0.0,
          'matrix': [
            1.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            1.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            1.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            1.0,
            0.0,
          ],
        },
        {
          'id': 'saturation',
          'value': 0.0,
          'matrix': [
            1.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            1.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            1.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            1.0,
            0.0,
          ],
        },
        {
          'id': 'exposure',
          'value': 0.0,
          'matrix': [
            1.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            1.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            1.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            1.0,
            0.0,
          ],
        },
        {
          'id': 'hue',
          'value': 0.0,
          'matrix': [
            1.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            1.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            1.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            1.0,
            0.0,
          ],
        },
        {
          'id': 'temperature',
          'value': 0.0,
          'matrix': [
            1.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            1.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            1.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            1.0,
            0.0,
          ],
        },
        {
          'id': 'sharpness',
          'value': 0.0,
          'matrix': [
            1.0,
            0.0,
            0.0,
            0.0,
            -0.0,
            0.0,
            1.0,
            0.0,
            0.0,
            -0.0,
            0.0,
            0.0,
            1.0,
            0.0,
            -0.0,
            0.0,
            0.0,
            0.0,
            1.0,
            0.0,
          ],
        },
        {
          'id': 'luminance',
          'value': 0.0,
          'matrix': [
            1.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            1.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            1.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            1.0,
            0.0,
          ],
        },
        {
          'id': 'fade',
          'value': 0.0,
          'matrix': [
            1.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            1.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            1.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            1.0,
            0.0,
          ],
        },
      ],
    },
    {
      'layers': [
        {'id': 'A'},
        {'id': 'B'},
        {'id': 'C'},
        {'id': 'D'},
        {'id': 'E'},
      ],
    },
  ],
  'references': {
    'A': {
      'x': 0.0,
      'y': 0.0,
      'rotation': 0.0,
      'scale': 1.5982142857142856,
      'flipX': false,
      'flipY': false,
      'interaction': {
        'enableMove': true,
        'enableScale': true,
        'enableRotate': true,
        'enableSelection': true,
      },
      'type': 'emoji',
      'emoji': '😛',
    },
    'B': {
      'x': 0.0,
      'y': 0.0,
      'rotation': 0.0,
      'scale': 1.0,
      'flipX': false,
      'flipY': false,
      'interaction': {
        'enableMove': true,
        'enableScale': true,
        'enableRotate': true,
        'enableSelection': true,
      },
      'type': 'text',
      'text': 'Hello World',
      'colorMode': 'backgroundAndColor',
      'color': 4281073408,
      'background': 4278190080,
      'align': 'center',
      'fontScale': 1.0,
    },
    'C': {
      'x': 9.100000000000023,
      'y': 76.20000000000005,
      'rotation': 0.0,
      'scale': 1.0,
      'flipX': false,
      'flipY': false,
      'interaction': {
        'enableMove': true,
        'enableScale': true,
        'enableRotate': true,
        'enableSelection': true,
      },
      'type': 'paint',
      'item': {
        'mode': 'arrow',
        'offsets': [
          {'x': 5.0, 'y': 68.59999999999997},
          {'x': 70.60000000000002, 'y': 5.0},
        ],
        'color': 4294901760,
        'strokeWidth': 10.0,
        'opacity': 1.0,
        'fill': false,
      },
      'rawSize': {'w': 75.60000000000002, 'h': 73.59999999999997},
      'opacity': 1.0,
    },
    'D': {
      'x': -101.19999999999993,
      'y': -225.19999999999993,
      'rotation': -0.261798,
      'scale': 0.6,
      'flipX': false,
      'flipY': false,
      'interaction': {
        'enableMove': true,
        'enableScale': true,
        'enableRotate': true,
        'enableSelection': true,
      },
      'type': 'widget',
      'exportConfigs': {'networkUrl': 'https://picsum.photos/id/17/400'},
    },
    'E': {
      'x': 101.19999999999993,
      'y': 225.19999999999993,
      'rotation': 0.261798,
      'scale': 0.6,
      'flipX': false,
      'flipY': false,
      'interaction': {
        'enableMove': true,
        'enableScale': true,
        'enableRotate': true,
        'enableSelection': true,
      },
      'type': 'widget',
      'exportConfigs': {'networkUrl': 'https://picsum.photos/id/17/400'},
    },
  },
  'imgSize': {'width': 1024.0, 'height': 1792.0},
  'lastRenderedImgSize': {'width': 327.0, 'height': 572.0},
};
